modLoader="javafml" #mandatory

loaderVersion="[39,)" #mandatory

license="MIT"

[[mods]] #mandatory

modId="taloi" #mandatory

version="${file.jarVersion}" #mandatory

displayName="That's A Lot Of Items" #mandatory

displayURL="https://www.curseforge.com/minecraft/mc-mods/thats-a-lot-of-items" #optional

logoFile="logo_banner.png" #optional

credits="Content, code, and art by NewJumper" #optional

authors="NewJumper" #optional

description='''
A mod about adding a whole lot more into the world of Minecraft.
'''

[[dependencies.taloi]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[39,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.taloi]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
