modLoader="javafml"
loaderVersion="[40,)"
license="AGPL-3.0"

[[mods]]
    modId="taloi"
    version="0.17.1"

    displayName="That's A Lot Of Items"
#     displayURL="https://www.curseforge.com/minecraft/mc-mods/thats-a-lot-of-items"
#     authors="NewJumper"
    credits="All art, code, textures, and concepts by NewJumper"
    logoFile="logo_banner_dark.png"

    description='''A mod that features a bunch of random stuff dumped into a block game.'''

[[dependencies.taloi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    side="BOTH"

[[dependencies.taloi]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    side="BOTH"

