blank_issues_enabled: false
contact_links:
  - name: CurseForge
    url: https://www.curseforge.com/minecraft/mc-mods/thats-a-lot-of-items
    about: Download the mod and try it for yourself on CurseForge!
